### ISSUE TITLE
influxDBThresholdError More details required

### ISSUE THREAD

**Issue by kamalshingala** [mderevyankoaqa/jmeter-influxdb2-listener-plugin#60]
Hi Michael, Thank you for building such a useful plugin. I was implementing this for one of my current performance test and wanting to understand a little bit more about influxDBThresholdError. From documentation, I can see that it’s configurable parameter and is not Malloy set to 5.

1. Can you please explain what do you mean by the error one by one reach 5 then it will stop importing data to InfluxDB. Do you mean the errors while sending data to InfluxDB or some other error?
2. Can you please explain a scenario when this can happen?

Thanks,
Kamal

**Comment by kamalshingala** [comment]
I created an issue by mistake when this should be in discussion. Apologies.

**Comment by mderevyankoaqa** [comment]
@kamalshingala,

influxDBThresholdError is the option to set the amount of the failures which can be occurred while sending the data to  InfluxDB. 

So let's answer your questions:
1. You are right, its errors while sending data to InfluxDB. 
2. Can be the errors: 
 a. network issues lead to InfluxDB unavailability while metrics sending, 
 b. not proper configuration of the InfluxDB endpoints and settings in the plugin, lack of the permissions
 c. some errors to import the data object (InfluxDB returns error for some reason)

So the idea is to give 5 attempts to send the data for example the network-related issue has occurred (the case "a"); there is a chance to send the metrics when the network-related issue is solved while the test.
The test will not be broken if "b", and "c" happened, the plugin will stop the data gathering and the log will be flushed. 

Since we have batches - the data is stored in memory; the plugin cleans the batch with data once data imported, but when we have the case "a" there is choose 
1. to clean failed batches (not implemented) 
2. save data and try to import a few times (now its implemented) 

BR
Mike

**Comment by kamalshingala** [comment]
Thank you for explaining this. We can close this.

**Comment by VoltHertz** [comment]
Hi, im actively using your plugin, but everytime i get a error with: max key length exceeded: #### > 65535 i lost the track of errors. Is there a parameter to limit the sixe o key length it gets from failed requests on j-meter, so it dosent stop the test monitoring but still get the the info of the error? Like at least import the 65534 from the begginig of the error? I dont want to lose errors control of jmeter.
